Desktop/heruko 2/Farzi/force-app/main/default/objects/Account/fields/Ready_to_migrate_to_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_migrate_to_Heroku__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to migrate to Heroku</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ready_to_migrate_to_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_migrate_to_Heroku__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to migrate to Heroku</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/Configuration_Heroku__c.object-meta.xml
<CustomObject>
    <label>Configuration Heroku</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Test heroku Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Herokus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Fields_1_APIs__c.field-meta.xml
<CustomField>
    <fullName>Fields_1_APIs__c</fullName>
    <label>Fields 1 APIs</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_2__c</fullName>
    <label>Filter Condition 2</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_3__c</fullName>
    <label>Filter Condition 3</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_4__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_4__c</fullName>
    <label>Filter Condition 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_2_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_2_API_Name__c</fullName>
    <label>Object 2 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_3_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_3_API_Name__c</fullName>
    <label>Object 3 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_4_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_4_API_Name__c</fullName>
    <label>Object 4 API Name</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Object_5_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_5_API_Name__c</fullName>
    <label>Object 5 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Ready_to_migrate_to_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_migrate_to_Heroku__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to migrate to Heroku</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Schedule_By__c.field-meta.xml
<CustomField>
    <fullName>Schedule_By__c</fullName>
    <label>Schedule By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>weekly</fullName>
            </value>
            <value>
                <fullName>monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Starts_At__c.field-meta.xml
<CustomField>
    <fullName>Starts_At__c</fullName>
    <label>Starts At</label>
    <type>Time</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Opportunity/fields/Ready_to_migrate_to_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_migrate_to_Heroku__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to migrate to Heroku</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DebugAnonymouseCode.cls
// Class created to hold Debug anonymouse code for time save
public class DebugAnonymouseCode {
/*

//For Testing purpose pass configuration Heroku Name in where condition
List<Configuration_Heroku__c> confi=[Select Id,Date__c,Fields_1_APIs__c,Fields_2_APIs__c,Fields_3_APIs__c,Fields_4_APIs__c,Fields_5_APIs__c,Filter_Condition_1__c,Filter_Condition_2__c,Filter_Condition_3__c,Filter_Condition_4__c,Filter_Condition_5__c,Object_1_API_Name__c,Object_2_API_Name__c,Object_3_API_Name__c,Object_4_API_Name__c,Object_5_API_Name__c,Runs_on__c,Schedule_By__c,Starts_At__c,Status__c from Configuration_Heroku__c where name='H-00094'];
 HerokuSyncBatchApexHelper.getHerokuObjData(confi);

// Run Below code to revert back to false for Testing purpose 
for(opportunity c:[Select id from opportunity]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(contact c:[Select id from contact]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(account c:[Select id from account]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(case c:[Select id from case]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(lead c:[Select id from lead]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}



 */
}