force-app/main/default/objects/Heroku_Sync_Settings__c/Heroku_Sync_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Heroku Sync Settings</label>
</CustomObject>

force-app/main/default/objects/Heroku_Sync_Settings__c/fields/Encryption_Key_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Encryption_Key_Heroku__c</fullName>
    <label>Encryption Key (Heroku)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Heroku_Sync_Settings__c/fields/Init_Vector_Heroku__c.field-meta.xml
<CustomField>
    <fullName>Init_Vector_Heroku__c</fullName>
    <label>Init Vector (Heroku)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HerokuCalloutHandler.cls
public class HerokuCalloutHandler  implements HerokuSync_Interface{

    public static List<sObject> syncRecords(List<sObject> records){
        HTTPRequest req = new HTTPRequest();
        String endpoint = HerokuSyncUtils.getEndpoint(null);
        endpoint += HerokuSyncUtils.HEROKU_ENDPOINT_SYNC_RECORDS;
        req.setEndpoint(endpoint);
        req.setBody(HerokuSyncUtils.encryptData(records));
        HTTPResponse res = HerokuSyncUtils.sendRequestToHeroku(req);
        return getResultRecords(res);
    }
    
    public static List<sObject> searchRecords(String searchTerm){
        HTTPRequest req = new HTTPRequest();
        String endpoint = HerokuSyncUtils.getEndpoint(null);
        endpoint += HerokuSyncUtils.HEROKU_ENDPOINT_SEARCH_RECORDS;
        endpoint += '?searchTerm=' + searchTerm;
        req.setEndpoint(endpoint);
        HTTPResponse res = HerokuSyncUtils.sendRequestToHeroku(req);
        return getResultRecords(res);
    }

    public static List<sObject> getResultRecords(HTTPResponse res){
        HerokuSyncUtils.HerokuResponseWrapper wrap = (HerokuSyncUtils.HerokuResponseWrapper)JSON.deserialize(res.getBody(), HerokuSyncUtils.HerokuResponseWrapper.class);
        Heroku_Sync_Settings__c hss = HerokuSyncUtils.getSyncConfiguration();
        String decryptedString = Crypto.decrypt(
            HerokuSyncUtils.HEROKU_ENCRYPTION_ALGORITHM,
            EncodingUtil.base64Decode(hss.Encryption_Key_Heroku__c),
            EncodingUtil.base64Decode(hss.Init_Vector_Heroku__c),
            EncodingUtil.base64Decode(wrap.result)
        ).toString();
        return (List<sObject>)JSON.deserialize(decryptedString, List<sObject>.class);
    }
}