force-app/main/default/objects/Configuration_Heroku__c/Configuration_Heroku__c.object-meta.xml
<CustomObject>
    <label>Configuration Heroku</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Test heroku Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Herokus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_2_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_2_API_Name__c</fullName>
    <label>Object 2 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_3_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_3_API_Name__c</fullName>
    <label>Object 3 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_4_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_4_API_Name__c</fullName>
    <label>Object 4 API Name</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Object_5_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_5_API_Name__c</fullName>
    <label>Object 5 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ConfigurationHerokuTriggerTest.cls
@isTest
public class ConfigurationHerokuTriggerTest {
    @TestSetup
    static void makeData(){
        Configuration_Heroku__c newConfig = new Configuration_Heroku__c();
        newConfig.Object_1_API_Name__c = 'Test Object';
        newConfig.Object_2_API_Name__c = 'Test Object';
        newConfig.Object_3_API_Name__c = 'Test Object';
        newConfig.Object_4_API_Name__c = 'Test Object';
        newConfig.Object_5_API_Name__c = 'Test Object';
        newConfig.Status__c = 'Active';
        insert newConfig;
    }

    @isTest public static void testMaxNumberOfSyncedObjects(){
        Configuration_Heroku__c newConfig = new Configuration_Heroku__c();
        newConfig.Object_1_API_Name__c = 'Test Object';
        newConfig.Status__c = 'Active';
        Test.startTest();
            Database.SaveResult tooManyObjectsSyncedResult = Database.insert(newConfig, false);
        Test.stopTest();
        System.assert(tooManyObjectsSyncedResult.isSuccess() == false, 'Result should not be successful');
        System.assert(tooManyObjectsSyncedResult.getErrors().size() == 1);
    }
}