force-app/main/default/objects/Configuration_Heroku__c/Configuration_Heroku__c.object-meta.xml
<CustomObject>
    <label>Configuration Heroku</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Test heroku Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Herokus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Fields_1_APIs__c.field-meta.xml
<CustomField>
    <fullName>Fields_1_APIs__c</fullName>
    <label>Fields 1 APIs</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_2__c</fullName>
    <label>Filter Condition 2</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_3__c</fullName>
    <label>Filter Condition 3</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Filter_Condition_4__c.field-meta.xml
<CustomField>
    <fullName>Filter_Condition_4__c</fullName>
    <label>Filter Condition 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_2_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_2_API_Name__c</fullName>
    <label>Object 2 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_3_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_3_API_Name__c</fullName>
    <label>Object 3 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Object_4_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_4_API_Name__c</fullName>
    <label>Object 4 API Name</label>
    <type>TextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Object_5_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_5_API_Name__c</fullName>
    <label>Object 5 API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuration_Heroku__c/fields/Schedule_By__c.field-meta.xml
<CustomField>
    <fullName>Schedule_By__c</fullName>
    <label>Schedule By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>weekly</fullName>
            </value>
            <value>
                <fullName>monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Configuration_Heroku__c/fields/Starts_At__c.field-meta.xml
<CustomField>
    <fullName>Starts_At__c</fullName>
    <label>Starts At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/HerokuSyncBatchApex.cls
/**
* Author           : Naveen
* Release          : To be confirmed
* Descrption       : This component will prepare the data to sync Heroku system*
* ClassName        : HerokuSyncBatchApex.cls 
* Test Class       : HerokuSyncBatchApexTest.cls
-----------------------------------------------------------------------------------------------------------
Ver       Date            Author                      Modification                   MathodName
-----------------------------------------------------------------------------------------------------------
1.0    16/01/2023       Naveen                         -                                   -
*/

global class HerokuSyncBatchApex implements Database.Batchable<sObject>
{
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id,Date__c,Fields_1_APIs__c,Fields_2_APIs__c,Fields_3_APIs__c,Fields_4_APIs__c,Fields_5_APIs__c,Filter_Condition_1__c,Filter_Condition_2__c,Filter_Condition_3__c,Filter_Condition_4__c,Filter_Condition_5__c,Object_1_API_Name__c,Object_2_API_Name__c,Object_3_API_Name__c,Object_4_API_Name__c,Object_5_API_Name__c,Runs_on__c,Schedule_By__c,Starts_At__c,Status__c FROM Configuration_Heroku__c where Status__c=\'Active\'';
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Configuration_Heroku__c> scope)
    {
        system.debug('Watch the scope size:::'+scope.size());
        for(Configuration_Heroku__c a : scope)
        {
            // HerokuSyncBatchApexHelper.getHerokuObjData();
        }
        HerokuSyncBatchApexHelper.getHerokuObjData(scope);
        // update scope;
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}