Desktop/heruko 2/Farzi/force-app/main/default/objects/Heroku_Error_Log__c/Heroku_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Heroku Error Log</label>
    <nameField>
        <displayFormat>HEL-{0000000}</displayFormat>
        <label>Heroku Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Heroku Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Heroku_Error_Log__c/fields/Related_Records__c.field-meta.xml
<CustomField>
    <fullName>Related_Records__c</fullName>
    <label>Related Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/objects/Heroku_Error_Log__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Desktop/heruko 2/Farzi/force-app/main/default/classes/HerokuErrorLog_Utils.cls
public without sharing class HerokuErrorLog_Utils {
    public static void logError(HerokuSyncUtils.ConfigurationException e, List<sObject> relatedRecords){
        Heroku_Error_Log__c newLog = new Heroku_Error_Log__c();
        newLog.Description__c = e.getStackTraceString();
        newLog.Related_Records__c = JSON.serialize((new Map<Id,SObject>(relatedRecords)).keySet());
        newLog.Summary__c	 = e.getMessage();
        insert newLog;
    }
}